language: node_js
node_js:
  - 15
cache:
  npm: true
install:
  - npm install
script:
  - npm test
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: ebook/_book
  github-token: $GITHUB_TOKEN
  keep-history: true
  target_branch: gh-pages
  on:
    branch: master
branches:
  only:
    - master
after_success:
  - bash <(curl -s https://codecov.io/bash)
